service: panther

provider:
  name: aws
  runtime: nodejs12.x
  apiKeys:
    - panther

plugins:
  - serverless-offline

functions:
  panther:
    handler: handler.panther
    events:
      - http:
          path: api/Panther
          method: get
          private: true
          request:
            parameters:
              querystring:
                host: true
                path: true
    timeout: 30
